### ISSUE TITLE
Possibly no support for Opera GX: 

### ISSUE THREAD

**Issue by TheHedgehogSonic** [Anarios/return-youtube-dislike#101]
### Browser

Opera GX

### Browser Version

Version 4.1.1

### Extension or Userscript?

Userscript

### Extension/Userscript Version

Version 4.13.6138

### Video link where you see the problem

https://www.youtube.com/watch?v=BG5sVag_0eQ

### What happened?

I still can't see dislikes.

**Comment by DARKDRAGON532** [comment]
What userscript manager are you using?

**Comment by TheHedgehogSonic** [comment]
I use TamperMonkey.

**Comment by DARKDRAGON532** [comment]
> I use TamperMonkey.
the api is down right now and thats what tampermonkey relies on at the moment, sorry for the inconvenience

**Comment by TheHedgehogSonic** [comment]
That's too bad. Any idea when it'll be back up?

**Comment by mgcountss** [comment]
It should be back now.

**Comment by TheHedgehogSonic** [comment]
Hooray! It works!

**Comment by mattphelps-8451** [comment]
@mgcountss @TheHedgehogSonic 
You can use the Chrome web store's extension instead of the userscript for all Chromium browsers, which includes Opera.

See me enabling it below
<img width="1154" alt="Screen Shot 2021-12-01 at 1 40 10 AM" src="https://user-images.githubusercontent.com/79610204/144192138-03930d5d-bf66-4147-8f0a-57c36066d8cb.png">
:

**Comment by thesusian** [comment]
Can be closed @Anarios
