### ISSUE TITLE
(Feature Request): Let creators share their dislike API

### ISSUE THREAD

**Issue by Avogard** [Anarios/return-youtube-dislike#134]
### Extension or Userscript?

Extension

### Request or suggest a new feature!

Unfortunately, soon the API for dislikes will become private. However, it will be still accessible by creators, so you can let them share the count with the extension. A lot of creators (possibly the majority) don't support the removal of dislikes, so you can contact them and turn this into a massive public movement.

### Ways to implement this!

Make an option for creators to share their credentials, as simple as possible. Of course, not all of them will share: so you can mark real dislikes with certain color, whereas evaluated ones leave unmarked. After the implementation, some public relations work will have to be done.

### Can you work on this?

- [X] Yes
- [ ] No

**Comment by Frontesque** [comment]
This is already planned

**Comment by niwla23** [comment]
An option would also be to ask creators to share an api key to fetch their dislikes. These could be collected in the backend and could be fetched all 4 hours or so.. If there are more than a ~1000 creators sharing their keys, a distributed approach would probably be the best. So you create a worker tool that one can run in the background which will fetch an api key from time to time and send back the results. Maybe this could be implemented using some sort of proof of stake thing because in theory everyone could simply provide fake stats this way.
