### ISSUE TITLE
(Feature Request): Gather dislike/like data before it goes away

### ISSUE THREAD

**Issue by RyannDaGreat** [Anarios/return-youtube-dislike#178]
### Extension or Userscript?

Both

### Request or suggest a new feature!

Could we please implement a feature that (with opt-in permission of each user, of course) sends what video people are watching along with the like/dislike ratio for future machine learning purposes? Since this data will only be available for another week and a half, it would be really helpful to gather data on what videos people care about, which ones are liked and disliked so that we could use sentiment analysis or some other machine learning technique in the future to predict the dislike ratio of videos.

I've already begun collecting a dataset of a few million YouTube videos' likes/dislikes for this purpose, but they're mostly by going to related videos of related videos of related videos etc...not necessarily the same distribution of videos that people actually care about. If anybody wants this data I'd be more than happy to share it.

### Ways to implement this!

We need to set up a central server that will receive youtube URL's along with their dislike counts from users using this plugin.
We also need some front-end notification that asks users if it's ok to send this data to the server, for privacy purposes.

### Can you work on this?

- [X] Yes
- [ ] No

**Comment by sy-b** [comment]
> I've already begun collecting a dataset of a few million YouTube videos' likes/dislikes for this purpose, but they're mostly by going to related videos of related videos of related videos etc...not necessarily the same distribution of videos that people actually care about. If anybody wants this data I'd be more than happy to share it.

Are you aware about Archive Team's project to scrape all YouTube dislikes?
https://tracker.archiveteam.org/youtube-dislikes/

If you are willing to help click on "Run your own ArchiveTeam Warrior" & follow the instructions

---

>We need to set up a central server that will receive youtube URL's along with their dislike counts from users using this plugin.
We also need some front-end notification that asks users if it's ok to send this data to the server, for privacy purposes.

That's a tedious thing to implement. If you are interested, check #109 & this https://github.com/Anarios/return-youtube-dislike/issues/109#issuecomment-985711748 .
To prevent vandalization of DB, user authentication and resisting bot scripts are just the tip of the iceberg.

---

>for future machine learning purposes

In that case we'll need more parameters that just what Archive Team is scraping.
I have no idea what those parameters could be. Do you have any?

There [this](https://kth.diva-portal.org/smash/get/diva2:1214428/FULLTEXT01.pdf) on that topic. Its using sentiment analysis on comments.
In my opinion, depending on audience which just watches one video & then comments, isn't that good idea. Simply because if a someone finds one video useful then it is likely that it'll be the only one that the person has seen & will surely comment positively, not considering the fact that, there might be a better video. And this happens a lot.
So, it might not be an excellent idea, but its not even a bad idea.

On top of that, it'll need pretty high end resources. This project is funded by [donations](https://www.patreon.com/returnyoutubedislike), & I believe that it shouldn't be relied upon for long term.
