### ISSUE TITLE
(Bug): Doesn't query dislikes for youtube clips

### ISSUE THREAD

**Issue by WormChickenWizard** [Anarios/return-youtube-dislike#180]
### Browser

Brave

### Browser Version

1.32.113 Chromium: 96.0.4664.45 (Official Build) (64-bit)

### Extension or Userscript?

Extension

### Extension/Userscript Version

1.1.0.0

### Video link where you see the problem

https://youtube.com/clip/Ugkx-vmGREh9elsBRbgrwnJqMwhQSaxr5YsW

### What happened?

Anytime that I navigate to a YouTube clip (i.e https://youtube.com/clip/*), dislikes are not queried.

**Comment by mphelp** [comment]
A clip's ID looks quite dissimilar to a video ID. But fortunately, a clip's stats appear to be a carbon copy of the original video's stats. Even the hidden "averageRating":4.9558887

If you click on "watch full video" in the clip linked above, you'll be brought to https://www.youtube.com/watch?v=1Ntwv1z6WAk. 

We can archive the stats of the original video from this link instead of the clip to keep everything consistent, since the stats are identical.

**Comment by Frontesque** [comment]
This is an issue with the extension only having permissions to access "youtube.com/watch?v=*" links. It isn't able to access "youtube.com/clip/*". Im not sure if the element layout is similar to how it is on the normal videos but I can look into it. This might be a simple fix.

**Comment by Frontesque** [comment]
After looking into it, We'd need to find some way to get the original video id from the clip. It's not really a high priority right now as there are more important features that should be implemented first. This can be a thing for later

**Comment by mphelp** [comment]
@Frontesque turns out there's always a meta tag with the exact ID

**Comment by WormChickenWizard** [comment]
I'm now running version 1.1.0.2 of the extension and it still isn't showing the number of dislikes on the clips. I looked at #215 and its trying to match /clips/* when it should be /clip/* (notice there's a lack of an s).

**Comment by mphelp** [comment]
@WormChickenWizard Thanks for finding my typo. Already merged in #267
