### ISSUE TITLE
Use Babel for UserScripts

### ISSUE THREAD

**Issue by DARKDRAGON532** [Anarios/return-youtube-dislike#27]
This will provide backward compatibility for people using older browsers, I don't know why people will be using old browsers but it adds some support for them. 

Thoughts?

**Comment by SpizWhy** [comment]
i use explorer

**Comment by favna** [comment]
Instead of using babel you'd be much better of using esbuild, swc or rollup. They're all much faster and more efficient bundling tools.

Anyway I personally don't think older browsers should be supported. It's not worth the development overhead / pain. If people don't want to update their browsers, that's on them.

**Comment by DARKDRAGON532** [comment]
I agree, but if you can use those tools to easily provide compatibility for old browsers that would be pretty nice. It isn't a priority though, after everything is much stable maybe I'll try working on the userscript for other userscript managers and older browsers.
