### ISSUE TITLE
(Feature Request): Remove the dislike count from videos with hidden likes

### ISSUE THREAD

**Issue by SirLich** [Anarios/return-youtube-dislike#279]
### Extension or Userscript?

Extension

### Request or suggest a new feature!

I suggest removing the 'dislike' count entirely from videos that have hidden likes. This would bring our extension more in line with how YouTube itself functions. 

Right now the extension shows the dislikes, and not the likes, which makes the video seem very negative, even when that's not the case.

I'm against adding tracked likes/dislikes for these videos, as it goes against the creators choice. If nothing else, it opens us up to attacks/bad PR: Let the creator choose!

Community discussion can be found in: #196 

196 has been duplicated a few times: #227 #269 

---

**This is not a duplicate issue. This task is actually suggesting the opposite solution to existing issues.**

### Ways to implement this!

Ask the YT api if likes are hidden or not. If they are, do not apply extension.

### Can you work on this?

- [ ] Yes
- [X] No

**Comment by GiorgioBrux** [comment]
There is a typo in the title, you probably wanted to type `likes` at the end.

Anyway I want to point out that like it's been said in #269 we can also try to show the like counter too instead of hiding the dislike one, or even maintain the status quo and show just the dislikes.

Like others have said it's up to Anarios to decide, so let's wait for him to chime in.

**Comment by pozhiloy-enotik** [comment]
There should be an option about showing likes

**Comment by Nightcaat** [comment]
This has been the behavior for a long time now. The dislike count currently says Disabled by Owner if this is the case.
