### ISSUE TITLE
(Feature Request): option to disable submit of likes/dislikes to the extension

### ISSUE THREAD

**Issue by himanshudabas** [Anarios/return-youtube-dislike#292]
### Extension or Userscript?

Extension

### Request or suggest a new feature!

An option to _not submit likes/dislikes_ to the extension should be given to the user.
submission of likes/dislikes to the extension can be enabled by default, but option should also be present to disable it.

### Ways to implement this!

an option could be added to the extension settings to toggle a button to disable submission of likes/dislikes.

a time based disable option can also be provided. similar to how we can mute notifications from an app for 1 hour, 2 hours or until the user turns the notifications back on.

### Can you work on this?

- [X] Yes
- [ ] No

**Comment by Anarios** [comment]
Good one, thanks.

**Comment by magnus-ISU** [comment]
So, I'm not saying this is exactly a bad idea, but what is the use case?

If you're voting on a video, it's presumably because you want to actually affect the vote tallies of the video.

**Comment by cupiditys** [comment]
just asking, doesn't that... defeat the purpose of disliking?

**Comment by himanshudabas** [comment]
> So, I'm not saying this is exactly a bad idea, but what is the use case?
> 
> If you're voting on a video, it's presumably because you want to actually affect the vote tallies of the video.

let's say for some video, I do not want the extension to know which video I liked or disliked.
or maybe someone is simply interested in using the extension for seeing other people's likes/dislikes but doesn't want to submit their own likes/dislikes.

> just asking, doesn't that... defeat the purpose of disliking?

I agree that this goes against what this extension is trying to do. what if everyone stops submitting their likes/dislikes?
well, that's a valid point. But people should also have an option to disable like/dislike submissions if they want to. Their reason could be anything. maybe Privacy?

One thing that I have mentioned above is "disabling the submission for a certain period of time, and then it re-enables itself. so that people won't forget to re-enable it after they are done with their privacy mode?

**Comment by magnus-ISU** [comment]
Hmm. While I think that privacy is important, and use Librewolf on my main computer because of it.

However, privacy (as in, keeping the server from knowing what your account is doing) just doesn't make sense as a goal when interacting on a public forum. I trust the developers of this extension, its FOSS for one thing. However, putting that aside, any malicious information they might extract from you (knowing what videos you watch is about the worst I can imagine) can be found just from your requests to query the dislike count, ignoring whether your dislikes are submitted or not.

Also, having it automatically turn back on defeats the purpose even more imo, and tells me that it just isn't a useful feature.

I don't think implementing this could do any harm, but I don't see the point. That's my 2 cents at least.

**Comment by himanshudabas** [comment]
> any malicious information they might extract from you (knowing what videos you watch is about the worst I can imagine) can be found just from your requests to query the dislike count, ignoring whether your dislikes are submitted or not.

that's technically not correct,
dislikes & likes are mapped with your `userId` and are stored in DB. On the other hand, api calls to get the dislike count provides somewhat less information about the user.
frontend/extension code is open-source, so we know what, when & how requests are being made from the client side.
so the only way to track someone from the backed is, if they store the **IP addresses along with all the query requests (fetch dislike count)**.
Now, if I want to hide that, I can simply disable submission and use a proxy.
(I know I am doing overkill here, but that's just because I wanted to explain that they can't track the user only tracking the dislike count fetch api calls)

> Also, having it automatically turn back on defeats the purpose even more imo, and tells me that it just isn't a useful feature.

coming to the second point, why do you think _it defeats the pupose even more_?
I also said that there would also be an option to disable submission till the user him/herself enable the submissions again.


That brings me to another point, What do you think about an option to disable the entire extension? just like how we can disable the adblockers temporarily?

PS: by this comment I am not trying to imply that the developers of this extensions are doing anything bad with the data, I am simply trying to explain how your point about tracking from get requests is not exactly 100% true.

**Comment by magnus-ISU** [comment]
I haven't actually looked through the source extensively because I mostly wanted to come here to ask for what issue 279 already asks for, so I'm not sure what I will continue to contribute much more on this issue ;p

But to answer your question, browsers already do (or should - firefox does, if Chromium/tampermonkey doesn't that's bad design) provide methods to disable extensions entirely. Reimplementing that in the extension is needless complexity, so wasted developer effort and also can confuse users.

As for why it defeats the purpose *even more* its because the implication a user would want to turn it back on and just might forget, so we're helping them out by re-enabling it. I don't know, like I've said this whole issue seems silly to me but maybe other people want it (such as, you) and in that case go ahead and add it in.

**Comment by himanshudabas** [comment]
@Anarios 
what do you think about this?

**Comment by Anarios** [comment]
@himanshudabas , while I agree that disabling submitting dislikes defies the purpose of the extension - it should be user's choice, even if we would like to collect that data - we shouldn't do it if the user doesn't want it

**Comment by Anarios** [comment]
I will be displaying a warning though, something along the line of "welp, now your votes don't mean anything, because they are not counted"

**Comment by himanshudabas** [comment]
where do you want to show this warning? in popup.html?
we can also change the extension icon when extension is disabled. like show a small red/yellow dot at the bottom right of the extension icon.

something like this maybe:

![image](https://user-images.githubusercontent.com/20219940/146071420-0b53b6f2-c2a8-463f-813c-7646684a30f1.png)
