### ISSUE TITLE
(Feature Request): Translate and Publish this Extension in more Languages

### ISSUE THREAD

**Issue by flpeters** [Anarios/return-youtube-dislike#349]
### Extension or Userscript?

Both

### Request or suggest a new feature!

YouTube is used in many different Countries, by people speaking many different languages.

There is a good chance that some of those people would also be interested in this Extension, but maybe the language barrier keeps them from finding this Extension (the browser add-on store doesn't easily show projects in other languages), or from understanding what it is.

Translating and Publishing this Extension in more Languages could bring a more diverse group of people to this Extension, ultimately improving the data used for extrapolating the like/dislike ratio for all users.

I believe working on this sooner rather than later is important, because over time other developers might create Extensions for specific languages first (maybe without even knowing that this Extension exists), which could lead to a split community.

In a sense it might be more important to focus on integrating other communities first, instead of improving the stuff the user can't see, in order to mitigate the creation of filter bubbles, and to detect design requirements for global use early, before it becomes too difficult to make changes.

### Can you work on this?

- [ ] Yes
- [X] No

**Comment by UnderscoreX5** [comment]
I am not 100% sure about the necessity of this honestly. Don't get me wrong, I do think that making the extension accessible to as much people as possible is surely beneficial but at the same time I don't really think that there is much of a language barrier. I tried searching for the extension on the chrome webstore using both the italian one, the french one and the english one, they all show the same result by just typing "Dislike" a word that's very likely to be known, so even if you don't know the full name of the extension you can find it easily. This was regarding the store itself but regarding the extension I don't think there's much to say: it simply doesn't display anything that needs translation (numbers are numbers).
Something that could be translated is instead the website (https://www.returnyoutubedislike.com/) since some people might actually stumble upon it first before the actual chrome/firefox store (even tough both Google and DDG display the chrome store first). I could provide some translations if needed. Let me know if I got something wrong.

**Comment by flpeters** [comment]
You're right that searching "Dislike" will generally work, but that doesn't cover people who don't speak at least a tiny amount of English, which is a very large number of people. Searching for any translation of Dislike in another language doesn't work, not to mention languages that use a different alphabet.

For the perfect example, try searching "no me gusta" in the Spanish chrome store. The first result that pops up is this [Dislikes for YouTube](https://chrome.google.com/webstore/detail/dislikes-for-youtube/jpefmbpcbebpjpmelobfakahfdcgcmkl) Extension with 30.000+ users, which has been translated into 25 languages, while Return YouTube Dislike doesn't show up at all.

Translating the numbers is of course (somewhat) silly. What I'm talking about is the Landing Page and the Store Pages.

**Comment by UnderscoreX5** [comment]
You are right! Totally forgot about that aspect. Then this is a priority in my personal opinion, too bad it needs to be done by the main creator since it's google and firefox's stores.

**Comment by UnderscoreX5** [comment]
Perhaps @Anarios is the one that needs to publish the extention to more languages trough the chrome and ff store. I can happily provide any italian translation btw.

**Comment by kdpuvvadi** [comment]
is mean time, atleast website translation would be great for non english speaking people.

> even tough both Google and DDG display the chrome store first)

for me it's website first, verge's article and then chrome store. i think it mostly depends on your search history with search engine i guess
