### ISSUE TITLE
(Bug): Youtube Redux Like/Dislike Bar

### ISSUE THREAD

**Issue by MrSkullium** [Anarios/return-youtube-dislike#38]
### Browser

Firefox

### Browser Version

Firefox 84.0b8

### Extension or Userscript?

Extension

### Extension/Userscript Version

0.0.0.8

### Video link where you see the problem

https://www.youtube.com/watch?v=ussCHoQttyQ

### What happened?

I know this may be a low priority and niche but with the Use green/red colors for likes/dislikes bar and Recreate old video page layout options on the Youtube Redux Addon, this addon overrides the layout and colors and makes it look awkward. If you can, maybe have an option to have youtube redux override the looks of this plugin is possible. Thanks
![Screenshot (735)](https://user-images.githubusercontent.com/66441517/142958993-44452906-17ba-46ef-9e02-7dd219357692.png)

**Comment by toydotgame** [comment]
Might add that it's broken regardless of having _Use green/red colors for likes/dislikes bar_ or _Use green/red colors for likes/dislikes buttons_ on or off. Any combination of the two settings will still result in a secondary bar being displayed:
![image](https://user-images.githubusercontent.com/64190512/143535642-0a96d112-6c96-4a54-8182-aeb8ce0a0ded.png)
The actual like/dislike _icons_ are replaced by Redux, however.

I don't believe that Redux has updated any code regarding the Dislike Change; it seems to think a video is at 100% liked (full green bar) because the like count is the only count it receives on the page. Given that return-youtube-dislike uses the YouTube _API_, and Redux does not, perhaps functionality can be added to return-youtube-dislike that puts the accurate like/dislike counts in a part of the webpage that Redux is trying to access, and to specifically disable its own like ratio bar when Redux is detected to be installed [or something like that].

**Comment by toydotgame** [comment]
**PS:** Hopefully a fix in that way, using exact numbers, should also fix the _Show precise values for likes/dislikes_ option in Redux, too.

**Comment by MrSkullium** [comment]
Seems like youtube redux already made an update regarding this and fixing this issue. So i guess this is a case closed
![Screenshot (752)](https://user-images.githubusercontent.com/66441517/144772296-d20f62c7-23b5-4711-8fed-e5bc44720f5a.png)
.

**Comment by Anarios** [comment]
Great, they're fixing our bugs, thanks a lot to them - I simply never had time for this.

**Comment by toydotgame** [comment]
YouTube Redux actually just added the _Dislikes restoring compatibility_ option. I think their goal is to eliminate the need for this extension if a user already has Redux installed.
The thing is, Redux still has a few bugs of its own and doesn't seem to show dislikes on it's own. Adding return-youtube-dislike _and_ having Redux's option turned on means that the extensions will "fight over the dislike button" - but this ends up removing the secondary bar. (Redux doesn't know the right dislike amounts through, proven by the green bar being green and not red)
![image](https://user-images.githubusercontent.com/64190512/145550139-11dc9f8e-0c04-46d6-9cde-9a9089fa6686.png)
