### ISSUE TITLE
Integration with OpenDislikeAPI

### ISSUE THREAD

**Issue by hrichiksite** [Anarios/return-youtube-dislike#401]
I am working on a project called the OpenDIslikeAPI (which I started yesterday, also happy new year). I have explained what that project will do in its README. So, I am here just to explain how it can help RYD after it's done and also how it will work with RYD.

### How will it work?
Basically, the extension will make a request to its server asking about the dislikes, then the server will check if it (it refers to the video) is part of the list of videosID by known (known refers to creators signed up for OpenDislikeAPI) creators. If it gets a match, it will send my server/OpenDislikeAPI's server to get the details, then my code will check if the values are present in the cache (and fresh enough [less than 3 hrs old]), if yes then it will get it from there else it will call the youtube API with the access token asking about the API, as soon as it gets the payload, it will return it to RYD as response and asynchronously update the values in cache. This whole process should take about 200 to 500 ms (can be greater or lesser depending upon many things)

### Why do they have to trust you trust?
Well, I have written the reasons why in the repo readme, few main reasons are that 1) I am giving them the ability to view the code, audit what's running on the server to check if it's the same code running or not 2) pinky promise.

### Who would use this?
Well, any creator who makes good content and not free energy hoaxes will use this to connect their account to give people access to real stats, that people deserve.

### Why?
This helps save space, time, and power. RYD's servers now no longer need to store the data of videos published by creators who already signed up with us. RYD can now do the work it was really made for, detect bad junk content for all... Also, it would reduce operational costs for RYD which is essential as currently, RYD is just dependent on donations and is also free to use (as it should be). Also, RYD can use this to sometimes verify its guesswork with real data when the creator signs up.

### Who is currently working on this?
Only me currently.

> ### Want to help?
> Sure, make a PR and push it, would be happy to check it out.

**Comment by hrichiksite** [comment]
I can work on the OpenDIslikeAPI server code, not the extension code. I have never made an extension before, and I would be scared to break stuff.

**Comment by hrichiksite** [comment]
few questions: https://github.com/Anarios/return-youtube-dislike/issues/392#issuecomment-1003660773
and its answers: https://github.com/Anarios/return-youtube-dislike/issues/392#issuecomment-1003662431

**Comment by cyrildtm** [comment]
okay I read your answers. As you have seen I'm not so familiar with this side of programming (I'm an engineer/physicist) but I've known javascript for a while. My response to your answers: 

- Sure, as long as there is a feasible way to audit your actions. 
- Okay I get it now. So you just want to install an existing package to store data, but still at your place. That's fine to me. 
- haha What I meant was physically and financially supporting this project is equal to declaring war against Google and Youtube. That would be a huge conflict of interest, so I don't think he will ever do it.

**Comment by hrichiksite** [comment]
haha, I knew what you meant by the last one, it is just fun to mention Linus's socks and sandals lol (no offense Linus, I am truly your fan). Also, you don't fire a missile at your best friend youtube, that would be stupid. Tho its much less than that. Youtube did it for creators.

**Comment by hrichiksite** [comment]
Updated Issue for the better reading experience.

**Comment by hrichiksite** [comment]
Updated Issue for a better reading experience.

**Comment by Anarios** [comment]
Hi, thanks for proposal. A very similar service with very similar features is being implemented by me already. 

As soon as it's out of PoC - it will be opensource.

So for now I'll stick with my own solution.

**Comment by hrichiksite** [comment]
@Anarios I think it would be better to call an API and get the data instead of doing that in the function to get the requests as its 
1) faster
2) easier.
3) anyone can use my API to get data about likes instead of yours, that would further reduce the load on your servers.
4) creators just need to trust one service with their OAuth to give out the accurate dislike/like details.

**Comment by hrichiksite** [comment]
Also, it's better that one part does the work instead of everything. Adding this feature already made by you will add more complexity to your already complex backend and also increase the surface of attack for bad actors. So I recommend that you wait for a few days before shipping that code, and we may be done by then and you can implement our API in your code.

**Comment by irlcatgirl** [comment]
Going to add I like the idea of your project but believe Nodejs is a bad idea when you need to scale later. Node is a dependency nightmare up to the point they added a NPM Audit Command to try and find + fix outdated packages. I personally would not want to use it but there are those who love to use on the server and probably for good reasons. I may just be biased against JavaScript here but since I’m responding I’m going to add it anyways.

Given how many people use this extension it’ll be challenging to create a stable and secure API. Rushing server side code is bad for a security context. More review is needed before exposing the code to the Internet. I’m not saying it’s impossible for you to spend a weekend and get a functional API up and running only I would be skeptical about exposing it to 500,000 users right away. When running a large service you have to be careful to protect user privacy and security something you just can’t do with code written haphazardly over a weekend. This isn’t even to say your code will be bad only that I wouldn’t be comfortable using it personally without further review by multiple people occurring first.

Lastly, and I hate to be that person, where do you plan on hosting said API server? This would quickly exceed the free tier of many cloud services. Based on your age stated on the README, how do you plan on funding the servers needed for an API that’s going to hammered quickly? This isn’t intended to be biased against you but rather to get you thinking about what you need to do for your API to be successful with such a large amount of users. I have no preference on which API is used but would like these concerns to be addressed if you were API were to be implemented in the extension.

**Comment by hrichiksite** [comment]
Hi, there @irlcatgirl,

> a lot of discussions has taken place in discord about security with @sy-b and @syntaxblitz you can see that in the suggesting "OpenDislikeAPI" thread. https://discord.com/channels/909435648170160229/927484840159375381/927799035551694919

I would host the API in railway, it would exceed the free tier? yes, I fear so. I would be open to donations also would like RYD donating something from their donations.

Also, nodejs is the best language for this as it's very easy to understand for people who maybe don't know to code. For the dependency part, ah, I won't be using much, so I don't think that would be a problem.

Cheers,
Hrichik.

**Comment by irlcatgirl** [comment]
I disagree that NodeJS is best simply because it is as you describe it the easiest programming language. Most languages can be easily understood by people who don’t necessarily know how to code. 

I would not recommend an asynchronous programming language for most types of web applications as it leads to difficult to debug behavior.

In an application with high load I would recommend Golang being easiest and cloud native, Elixir being challenging as a functional language but designed for high load apps, or Java with GraalVM if you don’t mind complex configuration and long build times.

In my experience Node’s memory usage can be err unpredictable compared to other programming languages. Ultimately I can’t force you to choose a specific language but want to make these concerns know. 

Even if you only use ExpressJS and Mongoose as your dependencies you are ignoring the fact they have their own dependencies which could introduce bugs into your application.

As for Railway it’s going to depend on if CPU cores are shared and how much RAM your express app needs including to maintain a MongoDB connection. NodeJS assumes by default you have at least 1.5 GB to allocate to it so special configuration could be required.

Maybe railway does this for you. I found this blog post that may help you https://www.tomspencer.dev/blog/2016/10/01/running-a-node-dot-js-app-in-a-low-memory-environment/ it may or may not work, I would be concerned that it’s such a high request rate they will cut you off from the free tier. But you could still try them and let us know how it works. But suddenly throwing 10k requests per second is going to strain most servers.

You might get donation money but what happens if you do not and the API server goes down, how are extension users affected? It is going to harm adoption of the extension if the API keeps going down and people could uninstall out of frustration.

Thank you for your consideration of my concerns and insights I look forward to seeing the progress on your project regardless of which language you choose to use.

Also, I will take a look at that discord discussion thread :-)

**Comment by hrichiksite** [comment]
1) Maybe but I know NodeJS better than any other lang. It would be bad for many reasons to switch and learn a new lang for an imp project that needs to be completed fast.
2) ^
3) I don't know Go or elixir 
4) that would be not much of a problem I hope as the API would not be doing "much" complicated stuff
5) I think those projects have big communities to fix those bugs and hopefully before they reach me. Anyways, I would be querying a Redis with only a video id that I would check and clean before finding.
6) they are pretty friendly people there, I hope they will help me seek out a solution to this.
7) I have a 12 GB ram quad core VM running dogegram.xyz I could just host it there but then it, I would have access to via ssh and get a few things that would undermine the security things. also thanks for your link I would see that 
8) If the API server goes down, Cloudflare would serve reqs for known videos for a few hrs before expiring and showing the old responses again. or it could error out as the server not responding 502.
9) you're welcome
10) sure, it's confusing at first but reading through the thread you would understand :)

Cheers,
Hrichik.

**Comment by Milo123459** [comment]
> Hi, thanks for proposal. A very similar service with very similar features is being implemented by me already.
> 
> As soon as it's out of PoC - it will be opensource.
> 
> So for now I'll stick with my own solution.

Hey - can we just have a little diagram of how this is going to work? How would it fetch the dislikes?

**Comment by hrichiksite** [comment]
ya sure, i would post that here soon

**Comment by Milo123459** [comment]
> ya sure, i would post that here soon

I'm not asking about yours, I'm asking about Anarios' - I'm also interested in yours though so I can have a look and see how they compare.

**Comment by hrichiksite** [comment]
Anarios's one would be basic OAUTH and fetching flow

Cheers,
Hrichik

**Comment by Milo123459** [comment]
> Anarios's one would be basic OAUTH and data fetching flow
> 
> Cheers, Hrichik

Where has he said this?

**Comment by hrichiksite** [comment]
> Where has he said this?

I assume so as per the wording in other sources. @Milo123459

**Comment by Milo123459** [comment]
> > Where has he said this?
> 
> I assume so as per the wording in other sources. @Milo123459

Please can you share these sources?

**Comment by hrichiksite** [comment]
> > > Where has he said this?
> > 
> > 
> > I assume so as per the wording in other sources. @Milo123459
> 
> Please can you share these sources?

It's in discord, please join and search it there.

**Comment by Milo123459** [comment]
I have joined the discord and searched and got nothing.

**Comment by hrichiksite** [comment]
> I have joined the discord and searched and got nothing.

You are `salvage` from the railway right?

**Comment by Milo123459** [comment]
Yes.

**Comment by hrichiksite** [comment]
Hi @Anarios, a few things to say
It is extremely immoral, unethical, unfair, and just plain bad to just mute anyone mid-conversation just because you are having a disagreement, or more like you are unable to understand what I said in Discord so I was explaining but someone found me "annoying" and @S190 muted me randomly and reasoned it as "Harassment" (also he/he just claimed was annoyed by the fact that I was a so-called "child" and know nothing that is blatantly false, and discriminatory behavior) but I never was Hostile to anyone and was just answering questions and pitching my idea and product to LW as its better and zero trust. I appeal to be unmuted as the mute was on unfair grounds with nonsense reasoning.

Also,
I have invited you to the repository to add the 128bit or 32 char code for the enc. Please join and add the code in the following format `<yourName>:<32BitSuperSecrectCodeThatsSecure>` for example `hrichik:32BitSuperSecrectCodeThatsSecure` it would be split at `:`

Cheers,
Hrichik

**Comment by hrichiksite** [comment]
https://github.com/OpenDislikeAPI/Code/invitations

**Comment by Anarios** [comment]
Hi @hrichiksite, you've been politely refused several times now, but you just don't give up. 

We do not intend to use your project. That decision is final. Please stop spamming everyone affiliated with RYD with your proposals. One is enough - we know that you exist and if we change our opinion - we'll contact you, no need to ask several times a day.

**Comment by hrichiksite** [comment]
Hi @Anarios,
I am not requesting something like perks or something material. What I am asking is just:
1) unmute me plz, that was unfair anyways
2) Also I know that you know I exist. But I am sure I won't be ever contacted if I remain silent muted on the server but solving your doubts to pitch a better solution for all that would also allow for the widespread adoption of RYD because of things I mentioned before
3) I didn't mention you **for the project** more than 2 times in a particular day and not even more than 3 to 4 times in my stay in the discord server. Instead, I was actively helping you guys and pitching some other ideas that I thought might help.
4) I am requesting you to just spend 2 mins of your life setting an enc key on https://github.com/OpenDislikeAPI/Code/invitations

Cheers,
Hrichik.

**Comment by hrichiksite** [comment]
I would like to conduct a poll on who should hold the encryption key for the creator's refresh token.

Please vote by reacting to this message.

🏎️ - Demitrii or LessWrong or @Anarios 
☄️ - LMG or LTT or Linus from LTT or anyone from there like Anthony (only one person)
🔢 - MrBeast
🚀 - MarkRober

> If the person with the most number of votes chooses to not hold the key, I would try to contact the person who got 2nd most number of votes. If same, the poll would be held again.

**Comment by irlcatgirl** [comment]
@Anarios Can you lock this thread to contributors my email is getting flooded with this argument 😬

**Comment by hrichiksite** [comment]
> @Anarios Can you lock this thread to contributors my email is getting flooded with this argument 😬

that is not a reason for a thread to be locked, maybe just un-watch this issue

**Comment by hrichiksite** [comment]
https://docs.google.com/presentation/d/1fvidbuKVX4Xeaoxo6pxOTd__LrEqsVJw_oSMH4kTGl0/edit?usp=sharing

Please see how it will work, in this presentation.
