### ISSUE TITLE
(Bug): Wrong number of dislikes. 9 times wrong.

### ISSUE THREAD

**Issue by MonkeSmart** [Anarios/return-youtube-dislike#562]
### Browser

Google Chrome

### Browser Version

Version 100.0.4896.127 (Official Build)

### Extension or Userscript?

Extension

### Extension/Userscript Version

2.1.0.3

### Video link where you see the problem

https://www.youtube.com/watch?v=dQw4w9WgXcQ

### What happened?

I will not doxx myself (so the link is on a different video), I am the channel owner (around 10K), decided to test this extension. On my latest video (new upload), at the moment, I have (in my Analytics) 180 Likes 1 Dislike, a 99.4% ratio (1598 views). I check it with your extension from a different account and it says that the video has 9 (!) dislikes. What is this? Do other people with this extension will think that my video gets so many dislikes? How your extension gets its info? It's false.

### How to reproduce/recreate?

How to reproduce/recreate? Be a channel owner and look at your video analytics. Then compare to information from this extension.
What I want to know is why the hell it is SO wrong? 9 times wrong, to be precise. Don't advertise yourself as a truthful representation if you are THIS wrong.

**Comment by cyrildtm** [comment]
Ask your viewers use this extension and vote. The more people who watch you use it the more accurate it gets. This extension gets data from extension user's response. It can only get as accurate as how many people use it. 
It's totally possible there are 19 people using this extension voted up and 1 person voted down. It's a 95% like ratio and using your 180 likes, dislike number gets extrapolated to be 9. It's simple math. This model gets more and more stable as you get more extension users response.

**Comment by Alejandrogayol** [comment]
I can asegurate you that you won’t fond any other return dislikes addon better than this. Probably this is the one that isn’t a scam. Obviously, isn’t possible to get exact dislikes because that data is completely private. In a future, you will be able to submit your exact dislikes.

**Comment by MonkeSmart** [comment]
> Ask your viewers use this extension and vote. The more people who watch you use it the more accurate it gets. This extension gets data from extension user's response. It can only get as accurate as how many people use it. It's totally possible there are 19 people using this extension voted up and 1 person voted down. It's a 95% like ratio and using your 180 likes, dislike number gets extrapolated to be 9. It's simple math. This model gets more and more stable as you get more extension users response.

So, the extension gets data from extension user's response. Not the actual data. What a bs.

> I can asegurate you that you won’t fond any other return dislikes addon better than this. Probably this is the one that isn’t a scam

It gets the data from estimation based on its own internal data set it gets from tracking user data, so it is.

Alright, at least I understood why it's bs'ing SO hard. It's not good that people might see false numbers but it can't be helped, it seems.

**Comment by Alejandrogayol** [comment]
Well, making your dislike public is the entire purpose of disliking, so it makes sense that the extension gets user dislikes. That option can be easily disabled in settings if you don't want it. In most popular videos, dislike stats from RYD are almost exact to real ones from YT Studio shared by creators. It can't be perfect, but another addons just show 0 dislikes from all videos because they used to extract the official data, and now it's gone forever. Don't think in it like a scam, because the purpose is to be the better alternative to official dislikes and it has been hardly worked and perforned

**Comment by MonkeSmart** [comment]
"making your dislike public is the entire purpose of disliking, so it makes sense that the extension gets user dislikes"
wtf are you on about saying the most obvious, we are talking about FALSE dislike count, not about making dislikes visible in itself because it is the purpose of the extension that is called "return youtube dislike", why even talk about this? BRUH.
"Don't think in it like a scam, because the purpose is to be the better alternative to official dislikes"
it is, literally, false estimated data. A false "alternative" to what, true data? Do you have logic? Better lies than no info? You literally have this logic here: hey, let's write a book that tells that Earth is flat, then take every book about astronomy from kids and give them this book - "iT wiLL bE thE bEtTer alTernAtive tO oFficiAl" information that does not exist in open source, so they will think that Earth is flat because we made them believe this with false information. LMAO. Nah, better to see no dislikes than false numbers.
Devs, if you are reading, **MAKE IT CLEAR** to users that your data is **NOT TRUE**, but ONLY **ESTIMATED**. Do not hurt the creators. There is no way for you to get information about new videos (after API hide), scrapped data is only from old videos. "estimates extrapolated from extension user data" - make it very clear that you count dislikes ONLY from extension users, who are a small percentage of all users on YouTube.
Kinda stupid that by "closing" the issue it gets away from public eyes, but, I will now close it. No dev answered so who gives a sht, right?
Don't misinform people, update your description to be very clear about this.
Cheers.

**Comment by Alejandrogayol** [comment]
Well, the extension actually says in the information that data is estimated. If people don’t read it, that isn’t developers problem. It’s like saying that SponsorBlock it’s fake because it uses user segments instead of all actual sponsors.
With all respect, do you really care between 12.000 “real” dislikes and 13.500 “fake” dislikes, for example, in a video with 900.000 likes? You say “fake numbers” like if the extension randomizes a number every time you open a video. Your own case it’s like telling kids the earth is a little bit ovolus, when it’s actually perfecly spherical, but not that it’s flat. Weird example, I know.
Also - RYD has 8 million daily users, and the entire platform has 122 million daily users, according to [globalmediainsight.com](url). That’s a 6%.
¿Why do you have more dislikes on RYD than in YT Studio? Simple. The only one that disliked had RYD installed. People without the addon doesn’t use to dislike videos, because it doesn’t do apparently nothing. Anyways, you will be able to share your exact dislikes in a future from YT Studio to avoid this from happen again. But 180 likes and 9 dislikes, it’s for me still a great rating - even it isn’t the ideal for you.
Do you said that this issue was clossed to misdirect people, but this is not a rating website. It’s a site to solve people problems and bugs. If you hate the extension and you want to left it recorded -  just rate it in Chrome Web Store or Firefox Addons or write an article in a forum or a blog.
Remember that a SCAM it’s a fraud, usually to make the user download viruses or track him. This extension have montly costs to mantain it’s API working (over 3000 dislike requests per second), a high developement process and a lot of testing. It’s intention it’s not to lie users, even if some didn’t realize that stats are estimated.
I’m sorry about your video got more dislikes than real ones, and I suggest you trying to contact the owner (LessWrong) in Discord or by Email to overwrite your dislikes in the database.
