### ISSUE TITLE
(Feature Request): automatic dislike comment to add to video

### ISSUE THREAD

**Issue by natewrench** [Anarios/return-youtube-dislike#92]
### Extension or Userscript?

Both

### Request or suggest a new feature!

Using a script to automatically add a dislike comment to a video like "I dislike this video" 

### Ways to implement this!

Hook a function into the JavaScript table and use auto fill to populate the field then click submit comment

### Can you work on this?

- [ ] Yes
- [X] No

**Comment by MagentaPuppy** [comment]
would this be automatic as soon as you watch a video or only if you dislike it?

**Comment by luni3359** [comment]
From what I understand, it'd be only after clicking dislike.

**Comment by natewrench** [comment]
> From what I understand, it'd be only after clicking dislike.

Yes

**Comment by luni3359** [comment]
Yeah that's a pretty good idea. It would help everyone out in the end, even those not using the extension.

**Comment by laughingsheep** [comment]
The Problem here is that this would add a lot of Spam. Also Youtube's Comment algorithm would quickly shadow ban that type of comments. Your account would also have the risk of being flagged and/or deleted if too many dislike comments are posted.
Still this ideas is a nice idea to add to the calculating of the amount of dislikes.

**Comment by Anarios** [comment]
Could be considered spam
