### ISSUE TITLE
No dislikes on Vivaldi

### ISSUE THREAD

**Issue by ghost** [Anarios/return-youtube-dislike#967]
### Have you tried to find similar open issues?

- [X] Yes, this issue is not a duplicate

### Browser

Vivaldi

### Browser Version

6.2.3105.58

### Extension or Userscript?

Extension

### Extension/Userscript Version

3.0.0.12

### Video link where you see the problem

Youtube

### What happened?

I was previously able to use the extension on Vivaldi by simply adding it from the Chrome Web Store.

### How to reproduce/recreate?

Any YT video no dislikes.

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by Nightcaat** [comment]
I just tried Vivaldi 6.2.3105.58 on RYD v3.0.0.12 logged out with only uBlock Origin alongside it and it works fine for me.

The author has since deleted their account and I am unable to gather more information from them (such as what other extensions they have) so I will now close this issue. Feel free to make a new issue about this if needed.
