### ISSUE TITLE
Settings not working in Firefox

### ISSUE THREAD

**Issue by lChap701** [Anarios/return-youtube-dislike#996]
### Have you tried to find similar open issues?

- [X] Yes, this issue is not a duplicate

### Browser

Firefox

### Browser Version

120.0.1

### Extension or Userscript?

Extension

### Extension/Userscript Version

Version 3.0.12

### Video link where you see the problem

https://www.youtube.com/watch?v=HivQqTtiHVw

### What happened?

None of the settings I applied did anything.

### How to reproduce/recreate?

![Screenshot 2023-12-01 225321](https://github.com/Anarios/return-youtube-dislike/assets/57417221/cbd7a625-f073-403e-b6fb-750a7550c8f1)
![Screenshot 2023-12-01 225608](https://github.com/Anarios/return-youtube-dislike/assets/57417221/2dbb475f-d09e-454e-9e24-2ffcfbb4f6f3)

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by iG8R** [comment]
The same situation.

**Comment by cryo420** [comment]
idea for dev: since youtube IS doing this (again claimed as "protection" with data being "only for now" creator only), just use the archived dislike data & its related system & just render such, everytime & on all occurances yt trys this; are just straight up replace the entire html code of the like/dislike system via the extension (preferably this)

**Comment by Nightcaat** [comment]
I am not experiencing this issue on Firefox 121.0.1, RYD 3.0.0.14. Let me know if you are still having problems.

**Comment by Nightcaat** [comment]
Closing as resolved as this seems to no longer be an issue.
